### PR TITLE
Setup build environment with Make.

### PR DESCRIPTION
**Pull request by Shinyzenith**
Ignore the last commit typo, it's late..

### CODE REVIEW

**Review by actualdankcoder — CHANGES_REQUESTED** [review]
I think the linux binary [salmon](https://github.com/Shinyzenith/salmon/blob/main/salmon) is better off going into the releases section rather than being included in the source folder itself

**Comment by Shinyzenith** [comment]
Looks like that was included by mistake. Will remove.

**Comment by Shinyzenith** [comment]
Another thing, the binary is quite large for it's relatively small codebase. Can anything be done to optimize it or is that not a priority right now?

**Review by actualdankcoder — APPROVED** [review]

**Comment by actualdankcoder** [comment]
> Another thing, the binary is quite large for it's relatively small codebase. Can anything be done to optimize it or is that not a priority right now?

It's something that has to do with the web development library [gin](https://github.com/gin-gonic/gin/issues/1847), it's not something we can tackle at this stage but I don't see the file size growing any exponentially larger in the future

**Pull request merged**
